name: Go Build And Test (Windows)
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.18'
    - name: Test
      run: go test -v ./...
    - name: Build
      run: go build -v .
    - name: Artifact
      uses: actions/upload-artifact@v4
      with:
        name: dicom-tags.exe
        path: dicom-tags.exe