name: Release
on:
  push:
    tags:
      - 'v*'
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18'
      - name: Test
        run: go test -v ./...
      - name: Build
        run: go build -v .
      - name: Create Release
        id: create_release
        run: gh release create -p --notes "Alpha testing improvements" ${{ github.ref }} './dicom-tags#dicom-tags'
  windows:
    runs-on: windows-latest
    needs: ubuntu
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18'
      - name: Test
        run: go test -v ./...
      - name: Build
        run: go build -v .
      - name: Upload Release Asset
        run: gh release upload ${{ github.ref }} './dicom-tags.exe#dicom-tags.exe'
