name: Release
on:
  push:
    tags:
      - 'v*'
permissions:
  contents: write
jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18'
      - name: Test
        run: go test -v ./...
      - name: Build
        run: go build -v -ldflags="-X 'github.com/TimMullender/dicom-tags/cmd.Version=${{ github.ref_name }}'" .
      - name: Create Release
        run: gh release create -p --notes "Alpha testing improvements" ${{ github.ref }} './dicom-tags#dicom-tags'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  windows:
    runs-on: windows-latest
    needs: ubuntu
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.18'
      - name: Test
        run: go test -v ./...
      - name: Build
        run: go build -v -ldflags="-X 'github.com/TimMullender/dicom-tags/cmd.Version=${{ github.ref_name }}'" .
      - name: Upload Release Asset
        run: gh release upload ${{ github.ref_name }} './dicom-tags.exe#dicom-tags.exe'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
